services:
  traefik:  # http://traefik/
    image: traefik:v2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.web.address=:80"
  nginx:    # http://nginx/
    image: ghcr.io/wtnb75/dlabel:latest
    build: .
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
    - dlabel
    - traefik-nginx-monitor
    - --forever
    - --conffile
    - /etc/nginx/nginx-monitor.conf
  example:
    image: nginx
    labels:
      traefik.enable: 'true'
      traefik.http.middlewares.example.stripprefix.prefixes: /example/
      traefik.http.routers.example.entrypoints: web
      traefik.http.routers.example.middlewares: example
      traefik.http.routers.example.rule: PathPrefix(`/example/`)
      traefik.http.services.example.loadbalancer.server.port: '80'
  httpbin:
    image: mccutchen/go-httpbin
    labels:
      traefik.enable: 'true'
      traefik.http.middlewares.httpbin.stripprefix.prefixes: /httpbin/
      traefik.http.routers.httpbin.entrypoints: web
      traefik.http.routers.httpbin.middlewares: httpbin
      traefik.http.routers.httpbin.rule: PathPrefix(`/httpbin/`)
      traefik.http.services.httpbin.loadbalancer.server.port: '8080'
  op:
    image: alpine/curl
    command:
    - sleep
    - infinity
